### PR TITLE
Feat/authentication

### PR DESCRIPTION
**Pull request by bhavyaj12**
Added the following:

- Login Page
- Sign Up Page
- Logout page and logout in header

Authentication

### CODE REVIEW

**Review by kirti2602 — APPROVED** [review]

**Comment by kirti2602** [comment]
Looks good to me. Can merge. Btw great UI💎

**Review by rishmi5h — APPROVED** [review]
UI 👌
Looks good to merge.

**Comment by prath-dev** [comment]
UI looks Nice and Clean

**Comment by prath-dev** [comment]
Nice selection of Colors

**Pull request merged**
